=== julianromera/agronet-harverter/agrislegacy.dtd
<!--==========================================================================================================-->
<!-- 	legacy.dtd - This is the Document Type Definition prepared and used for the conversion of the AGRIS legacy dayta (1975-2004) to XML
It is based on the current DTD (http://purl.org/agmes/agrisap/dtd/) and has been prepared by the GILW  group on 18 February 2005
It provides more flexibility and has other ad hoc changes for AGROVOC and non AGROVOC terms -->
<!--==========================================================================================================-->
<!-- Namespaces URIs declarations -->
<!ENTITY agsns "http://purl.org/agmes/1.1/">
<!ENTITY dcns "http://purl.org/dc/elements/1.1/">
<!ENTITY aglsns "http://www.naa.gov.au/recordkeeping/gov_online/agls/1.2">
<!ENTITY dctermsns "http://purl.org/dc/terms/">
<!-- Convenience entities for XML namespace declarations -->
<!ENTITY % agsnsdecl "xmlns:ags CDATA #FIXED &quot;&agsns;&quot;">
<!ENTITY % dcnsdecl "xmlns:dc CDATA #FIXED &quot;&dcns;&quot;">
<!ENTITY % aglsnsdecl "xmlns:agls CDATA #FIXED &quot;&aglsns;&quot;">
<!ENTITY % dctermsnsdecl "xmlns:dcterms CDATA #FIXED &quot;&dctermsns;&quot;">
<!-- The root element -->
<!ELEMENT ags:resources (ags:resource+)>
<!ATTLIST ags:resources
	xmlns:ags CDATA #FIXED "http://purl.org/agmes/1.1/"
	xmlns:dc CDATA #FIXED "http://purl.org/dc/elements/1.1/"
	xmlns:agls CDATA #FIXED "http://www.naa.gov.au/recordkeeping/gov_online/agls/1.2"
	xmlns:dcterms CDATA #FIXED "http://purl.org/dc/terms/"
>
<!ATTLIST ags:resource
	ags:ARN ID #IMPLIED
>
<!ELEMENT ags:resource (dc:title+, dc:creator*, dc:publisher*, dc:date*, dc:subject+, dc:description*, dc:identifier*, dc:type*, dc:format*, dc:language*, dc:relation*, agls:availability*, dc:source*, dc:coverage*, dc:rights*, ags:citation*)>
<!-- ELEMENT title -->
<!ELEMENT dc:title (#PCDATA | dcterms:alternative)*>
<!ATTLIST dc:title
	xml:lang CDATA #IMPLIED
>
<!ELEMENT dcterms:alternative (#PCDATA)>
<!ATTLIST dcterms:alternative
	xml:lang CDATA #IMPLIED
>
<!-- ELEMENT creator -->
<!ELEMENT dc:creator (ags:creatorPersonal | ags:creatorCorporate | ags:creatorConference)*>
<!ELEMENT ags:creatorPersonal (#PCDATA)>
<!ELEMENT ags:creatorCorporate (#PCDATA)>
<!ELEMENT ags:creatorConference (#PCDATA)>
<!-- ELEMENT publisher -->
<!ELEMENT dc:publisher (ags:publisherName | ags:publisherPlace)*>
<!ELEMENT ags:publisherName (#PCDATA)>
<!ELEMENT ags:publisherPlace (#PCDATA)>
<!-- ELEMENT date -->
<!ELEMENT dc:date (dcterms:dateIssued*)>
<!ELEMENT dcterms:dateIssued (#PCDATA)>
<!ATTLIST dcterms:dateIssued
	scheme (dcterms:W3CDTF) #IMPLIED
>
<!-- ELEMENT subject -->
<!ELEMENT dc:subject (#PCDATA | ags:subjectClassification | ags:subjectThesaurus)*>
<!ATTLIST dc:subject
	xml:lang CDATA #IMPLIED
>
<!ELEMENT ags:subjectClassification (#PCDATA)>
<!ATTLIST ags:subjectClassification
	scheme (ags:ASC | ags:CABC | dcterms:DDC | dcterms:LCC | dcterms:UDC) #IMPLIED
>
<!ELEMENT ags:subjectThesaurus (#PCDATA)>
<!ATTLIST ags:subjectThesaurus
	xml:lang CDATA #IMPLIED
	scheme (ags:AGROVOC | AGROVOCIAD | AGROVOCCAD | AGROVOCUpTerms | proposedTerms | localTerms | ags:NALT | ags:ASFAT | dcterms:LCSH | dcterms:MeSH | ags:CABT) #IMPLIED
>
<!-- ELEMENT description -->
<!ELEMENT dc:description (ags:descriptionNotes | ags:descriptionEdition | dcterms:abstract)*>
<!ELEMENT ags:descriptionNotes (#PCDATA)>
<!ELEMENT ags:descriptionEdition (#PCDATA)>
<!ELEMENT dcterms:abstract (#PCDATA)>
<!ATTLIST dcterms:abstract
	xml:lang CDATA #IMPLIED
>
<!-- ELEMENT identifier -->
<!ELEMENT dc:identifier (#PCDATA)>
<!ATTLIST dc:identifier
	scheme (ags:IPC | ags:RN | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:DOI) #IMPLIED
>
<!-- ELEMENT type -->
<!ELEMENT dc:type (#PCDATA)>
<!ATTLIST dc:type
	scheme (dcterms:DCMIType) #IMPLIED
>
<!-- ELEMENT format -->
<!ELEMENT dc:format (dcterms:extent | dcterms:medium)*>
<!ELEMENT dcterms:extent (#PCDATA)>
<!ELEMENT dcterms:medium (#PCDATA)>
<!ATTLIST dcterms:medium
	scheme (dcterms:IMT) #IMPLIED
>
<!-- ELEMENT language -->
<!ELEMENT dc:language (#PCDATA)>
<!ATTLIST dc:language
	scheme (ags:ISO639-1 | dcterms:ISO639-2) #IMPLIED
>
<!-- ELEMENT relation -->
<!ELEMENT dc:relation (dcterms:isPartOf | dcterms:hasPart | dcterms:isVersionOf | dcterms:hasVersion | dcterms:isFormatOf | dcterms:hasFormat | dcterms:references | dcterms:isReferencedBy | dcterms:isIMPLIEDBy | dcterms:requires | dcterms:isReplacedBy | dcterms:replaces | ags:relationHasTranslation | ags:relationIsTranslationOf)*>
<!ELEMENT dcterms:isPartOf (#PCDATA)>
<!ATTLIST dcterms:isPartOf
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:hasPart (#PCDATA)>
<!ATTLIST dcterms:hasPart
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:isVersionOf (#PCDATA)>
<!ATTLIST dcterms:isVersionOf
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:hasVersion (#PCDATA)>
<!ATTLIST dcterms:hasVersion
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:isFormatOf (#PCDATA)>
<!ATTLIST dcterms:isFormatOf
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:hasFormat (#PCDATA)>
<!ATTLIST dcterms:hasFormat
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:references (#PCDATA)>
<!ATTLIST dcterms:references
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:isReferencedBy (#PCDATA)>
<!ATTLIST dcterms:isReferencedBy
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:isIMPLIEDBy (#PCDATA)>
<!ATTLIST dcterms:isIMPLIEDBy
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:requires (#PCDATA)>
<!ATTLIST dcterms:requires
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:isReplacedBy (#PCDATA)>
<!ATTLIST dcterms:isReplacedBy
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT dcterms:replaces (#PCDATA)>
<!ATTLIST dcterms:replaces
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT ags:relationHasTranslation (#PCDATA)>
<!ATTLIST ags:relationHasTranslation
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!ELEMENT ags:relationIsTranslationOf (#PCDATA)>
<!ATTLIST ags:relationIsTranslationOf
	scheme (ags:IPC | ags:PN | ags:ISBN | ags:JN | dcterms:URI | ags:RN | ags:DOI) #IMPLIED
>
<!-- ELEMENT availability -->
<!ELEMENT agls:availability (ags:availabilityLocation, ags:availabilityNumber)*>
<!ELEMENT ags:availabilityLocation (#PCDATA)>
<!ELEMENT ags:availabilityNumber (#PCDATA)>
<!-- ELEMENT source -->
<!ELEMENT dc:source (#PCDATA)>
<!-- ELEMENT coverage -->
<!ELEMENT dc:coverage (#PCDATA | dcterms:spatial | dcterms:temporal)*>
<!ELEMENT dcterms:spatial (#PCDATA)>
<!ATTLIST dcterms:spatial
	scheme (dcterms:Point | dcterms:ISO3166 | dcterms:TGN | dcterms:Box) #IMPLIED
>
<!ELEMENT dcterms:temporal (#PCDATA)>
<!ATTLIST dcterms:temporal
	scheme (dcterms:Period | dcterms:W3CDTF) #IMPLIED
>
<!-- ELEMENT rights -->
<!ELEMENT dc:rights (#PCDATA | ags:rightsStatement | ags:rightsTermsOfUse)*>
<!ELEMENT ags:rightsStatement (#PCDATA)>
<!ELEMENT ags:rightsTermsOfUse (#PCDATA)>
<!-- ELEMENT citation -->
<!ELEMENT ags:citation (ags:citationTitle | ags:citationIdentifier | ags:citationNumber | ags:citationChronology)*>
<!ELEMENT ags:citationTitle (#PCDATA)>
<!ATTLIST ags:citationTitle
	xml:lang CDATA #IMPLIED
>
<!ELEMENT ags:citationIdentifier (#PCDATA)>
<!ATTLIST ags:citationIdentifier
	scheme (ags:ISSN | ags:CODEN) #IMPLIED
>
<!ELEMENT ags:citationNumber (#PCDATA)>
<!ELEMENT ags:citationChronology (#PCDATA)>

=== julianromera/agronet-harverter/harvested_files/nivel_AGRIS/files_AGRIS/TN/TN75001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ags:resources SYSTEM "../../agrislegacy.dtd">
<ags:resources xmlns:ags="http://purl.org/agmes/1.1/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:agls="http://www.naa.gov.au/recordkeeping/gov_online/agls/1.2" xmlns:dcterms="http://purl.org/dc/terms/">
  <ags:resource ags:ARN="TN7500009">
<dc:title xml:lang="en">[Current statement concerning the cereals sector and production development [in Tunisia]</dc:title>
<dc:creator>
<ags:creatorCorporate>Ministere de l'Agriculture, Tunis (Tunisia). Direction de la Production Agricole</ags:creatorCorporate>
</dc:creator>
<dc:publisher><ags:publisherPlace>Tunis (Tunisia)</ags:publisherPlace>
</dc:publisher>
<dc:date>
<dcterms:dateIssued>Dec 1974</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">F00</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">E10</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">E70</ags:subjectClassification>
</dc:subject>
<dc:description><ags:descriptionNotes>5 tables. Received at CNDA Apr 1975</ags:descriptionNotes>
</dc:description>
<dc:type>V</dc:type>
<dc:format><dcterms:extent>13 p.</dcterms:extent></dc:format>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>TN</ags:availabilityLocation><ags:availabilityNumber>7500009</ags:availabilityNumber></agls:availability>
</ags:resource>
</ags:resources>

=== julianromera/agronet-harverter/harvested_files/nivel_AGRIS/files_AGRIS/OS/OS75001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ags:resources SYSTEM "../../agrislegacy.dtd">
<ags:resources xmlns:ags="http://purl.org/agmes/1.1/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:agls="http://www.naa.gov.au/recordkeeping/gov_online/agls/1.2" xmlns:dcterms="http://purl.org/dc/terms/">
  <ags:resource ags:ARN="OS7500012">
<dc:title xml:lang="en">[Report on commercialization of millet bread]</dc:title>
<dc:creator>
<ags:creatorPersonal>Diallo, H.</ags:creatorPersonal>
<ags:creatorCorporate>Institut de Technologie Alimentaire, Dakar (Senegal)</ags:creatorCorporate>
</dc:creator>
<dc:date>
<dcterms:dateIssued>(Dec 1974)</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">Q10</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">A50</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">E70</ags:subjectClassification>
</dc:subject>
<dc:identifier scheme="ags:RN">OMVS-ACCESS.No.--05057-74-RA</dc:identifier>
<dc:type>V</dc:type>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>OS</ags:availabilityLocation><ags:availabilityNumber>7500012</ags:availabilityNumber></agls:availability>
<ags:citation><ags:citationTitle>Bulletin d'Information - Institut de Technologie Alimentaire. Centre de Documentation (Senegal)</ags:citationTitle>
<ags:citationNumber>v. 3/4 p. 14-40</ags:citationNumber>
<ags:citationChronology>(Dec 1974)</ags:citationChronology>
</ags:citation>
</ags:resource>
  <ags:resource ags:ARN="OS7500015">
<dc:title xml:lang="en">[The research of IRAT in Senegal]</dc:title>
<dc:creator>
<ags:creatorCorporate>Primature du Senegal, Delegation Generale a la Recherche Scientifique; Institut de Recherches Agronomiques Tropicales et des Cultures Vivrieres, Paris (France)</ags:creatorCorporate>
</dc:creator>
<dc:publisher><ags:publisherName>Centre National de Recherches Agronomiques</ags:publisherName>
<ags:publisherPlace>Bambey (Senegal)</ags:publisherPlace>
</dc:publisher>
<dc:date>
<dcterms:dateIssued>10 Aug 1974</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">A50</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">F00</ags:subjectClassification>
</dc:subject>
<dc:type>V</dc:type>
<dc:format><dcterms:extent>125 p.</dcterms:extent></dc:format>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>OS</ags:availabilityLocation><ags:availabilityNumber>7500015</ags:availabilityNumber></agls:availability>
</ags:resource>
  <ags:resource ags:ARN="OS7500007">
<dc:title xml:lang="en">[Annual report Entomology 1973. Experimentation for implementation of cotton growth in Senegal]</dc:title>
<dc:creator>
<ags:creatorPersonal>Labonne, V.</ags:creatorPersonal>
<ags:creatorCorporate>Institut de Recherches du Coton et Textiles Exotiques, Kaolack (Senegal); Ministere du Developpement Rural, Dakar (Senegal). Direction des Services Agricoles; Fonds Europeen de Developpement (Senegal)</ags:creatorCorporate>
</dc:creator>
<dc:publisher><ags:publisherName>IRCT</ags:publisherName>
<ags:publisherPlace>Kaolack (Senegal)</ags:publisherPlace>
</dc:publisher>
<dc:date>
<dcterms:dateIssued>1974</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">F00</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">H10</ags:subjectClassification>
</dc:subject>
<dc:identifier scheme="ags:RN">FED-Project--3100-333-15-08</dc:identifier>
<dc:type>V</dc:type>
<dc:format><dcterms:extent>27 p.</dcterms:extent></dc:format>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>OS</ags:availabilityLocation><ags:availabilityNumber>7500007</ags:availabilityNumber></agls:availability>
</ags:resource>
  <ags:resource ags:ARN="OS7500001">
<dc:title xml:lang="en">[Annual report on experimentation for the implementation of cotton cultivation in Senegal. Section of genetics]</dc:title>
<dc:creator>
<ags:creatorPersonal>Pauly, S. (Institut de Recherches du Coton et des Textiles Exotiques, Paris (France))</ags:creatorPersonal>
<ags:creatorCorporate>Institut de Recherches du Coton et des Textiles Exotiques, Kaolack (Senegal); Ministere du Developpement Rural, Dakar (Senegal). Direction des Services Agricoles</ags:creatorCorporate>
</dc:creator>
<dc:publisher><ags:publisherName>IRCT</ags:publisherName>
<ags:publisherPlace>Kaolack(Senegal)</ags:publisherPlace>
</dc:publisher>
<dc:date>
<dcterms:dateIssued>Mar 1974</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">A50</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">F30</ags:subjectClassification>
</dc:subject>
<dc:type>V</dc:type>
<dc:format><dcterms:extent>35 p.</dcterms:extent></dc:format>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>OS</ags:availabilityLocation><ags:availabilityNumber>7500001</ags:availabilityNumber></agls:availability>
</ags:resource>
  <ags:resource ags:ARN="OS7500008">
<dc:title xml:lang="en">[Project for the development of cattle-breeding in eastern Senegal]</dc:title>
<dc:creator>
<ags:creatorPersonal>Diallo, M.</ags:creatorPersonal>
<ags:creatorCorporate>Ministere du Developpement Rural et de l'Hydraulique, Dakar (Senegal); United Nations Development Programme, Dakar (Senegal); International Bank for Reconstruction and Development, Dakar (Senegal)</ags:creatorCorporate>
</dc:creator>
<dc:publisher><ags:publisherName>Societe d'Aide Technique et de Cooperation</ags:publisherName>
<ags:publisherPlace>Dakar (Senegal)</ags:publisherPlace>
</dc:publisher>
<dc:date>
<dcterms:dateIssued>May 1974</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">L00</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">E10</ags:subjectClassification>
</dc:subject>
<dc:type>V</dc:type>
<dc:format><dcterms:extent>46 p.</dcterms:extent></dc:format>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>OS</ags:availabilityLocation><ags:availabilityNumber>7500008</ags:availabilityNumber></agls:availability>
</ags:resource>
  <ags:resource ags:ARN="OS7500024">
<dc:title xml:lang="en">[Quantitative survey of a sample of fauna from recent quaternary of Saint-Louis region (Senegal)]</dc:title>
<dc:creator>
<ags:creatorPersonal>Monteillet, J.</ags:creatorPersonal>
<ags:creatorCorporate>Institut Fondamental d'Afrique Noire, Dakar (Senegal)</ags:creatorCorporate>
</dc:creator>
<dc:date>
<dcterms:dateIssued>(1974)</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">F23</ags:subjectClassification>
</dc:subject>
<dc:description>
<ags:descriptionNotes>13 ref.</ags:descriptionNotes>
</dc:description>
<dc:identifier scheme="ags:RN">OMVS-ACCESS.NO.--05234-75-ET</dc:identifier>
<dc:type>V</dc:type>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>OS</ags:availabilityLocation><ags:availabilityNumber>7500024</ags:availabilityNumber></agls:availability>
<ags:citation><ags:citationTitle>Bulletin de l'Institut fondamental d'Afrique Noire. Serie A (Senegal)</ags:citationTitle>
<ags:citationNumber>v. 36(2) p. 257-290</ags:citationNumber>
<ags:citationChronology>(1974)</ags:citationChronology>
</ags:citation>
</ags:resource>
  <ags:resource ags:ARN="OS7500018">
<dc:title xml:lang="en">[Report of 1972 activity; survey and improvement of surroundings; bioclimatology: Meteorology of ISRA weather stations]</dc:title>
<dc:creator>
<ags:creatorCorporate>Delegation Generale a la Recherche Scientifique et Technique, Dakar (Senegal); Institut senegalais de Recherches Agricoles, Bambey (Senegal)</ags:creatorCorporate>
</dc:creator>
<dc:publisher><ags:publisherName>CNRA</ags:publisherName>
<ags:publisherPlace>Bambey (Senegal)</ags:publisherPlace>
</dc:publisher>
<dc:date>
<dcterms:dateIssued>Nov 1974</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">F10</ags:subjectClassification>
</dc:subject>
<dc:type>V</dc:type>
<dc:format><dcterms:extent>93 p.</dcterms:extent></dc:format>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>OS</ags:availabilityLocation><ags:availabilityNumber>7500018</ags:availabilityNumber></agls:availability>
</ags:resource>
  <ags:resource ags:ARN="OS7500021">
<dc:title xml:lang="en">[Preliminary results of experimental trawling campaign]</dc:title>
<dc:creator>
<ags:creatorPersonal>Brulhet, J.</ags:creatorPersonal>
<ags:creatorPersonal>Maigret, J.</ags:creatorPersonal>
<ags:creatorCorporate>Ministere du Developpement Industriel, Nouakchott (Mauritania). Direction des Peches</ags:creatorCorporate>
</dc:creator>
<dc:date>
<dcterms:dateIssued>(Dec 1973)</dcterms:dateIssued>
</dc:date>
<dc:subject>
<ags:subjectClassification scheme="ags:ASC">M10</ags:subjectClassification>
<ags:subjectClassification scheme="ags:ASC">M40</ags:subjectClassification>
</dc:subject>
<dc:identifier scheme="ags:RN">OMVS-ACCESS.NO--05176-73-ET</dc:identifier>
<dc:type>V</dc:type>
<dc:language scheme="ags:ISO639-1">Fr</dc:language>
<agls:availability><ags:availabilityLocation>OS</ags:availabilityLocation><ags:availabilityNumber>7500021</ags:availabilityNumber></agls:availability>
<ags:citation><ags:citationTitle>Bulletin du Laboratoire des Peches de Nouadhibou (Mauritania)</ags:citationTitle>
<ags:citationNumber>v. 2 p. 57-112</ags:citationNumber>
<ags:citationChronology>(Dec 1973)</ags:citationChronology>
</ags:citation>
</ags:resource>
</ags:resources>
